export enum USER_FEEDBACK_ITEM_TYPE {
  FEATURE_REQUEST = 'FEATURE_REQUEST',
  BUG = 'BUG'
}
export enum USER_FEEDBACK_ITEM_STATUS {
  OPEN = 'OPEN',
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETE = 'COMPLETE'
}

export enum USER_FEEDBACK_ITEM_VOTE {
  UPVOTE = 'UPVOTE',
  REMOVE_UPVOTE = 'REMOVE_UPVOTE'
}
