on:
  workflow_call:
    inputs:
      # controllable flow properties
      # do you want to deploy
      # do you want to run tests
      # do you want to notify on slack
      # do you want to use 7zip to package instead of zip
      should-deploy:
        required: true
        type: boolean
      should-deploy-as-server:
        required: false
        type: boolean
      should-run-unit-tests:
        required: true
        type: boolean
      should-notify-on-failure:
        required: true
        type: boolean
      should-unzip-editor: # macos requires an extra zip file on cicd
        required: false
        type: boolean
      should-install-timeout-macos:
        required: false
        type: boolean
      # godot export properties
      # specifies the workflow, name, branch and binary to download for the editor and template.
      editor-binary-workflow:
        required: true
        type: string
      editor-binary-name:
        required: true
        type: string
      # for when the binary name is not consistent like on macos.
      editor-binary-download:
        required: true
        type: string
      editor-binary-branch:
        required: true
        type: string
      editor-template-directory:
        required: true
        type: string
      template-binary-workflow:
        required: true
        type: string
      template-binary-name:
        required: true
        type: string
      template-binary-branch:
        required: true
        type: string
      export-template-file:
        required: true
        type: string
      # server properties
      server-pck-path:
        required: false
        type: string
      # game properties
      # the mirror environment configuration to use
      game-environment-cfg-name:
        required: true
        type: string
      # the export preset to use
      game-export-preset:
        required: true
        type: string
      # game output binary name
      game-binary-name:
        required: true
        type: string
      # gcp bucket name to upload to
      bucket-name:
        required: true
        type: string
      os:
        required: true
        type: string
      environment:
        required: false
        type: string
      url:
        required: false
        type: string
      itch-channel:
        required: false
        type: string
      itch-project-name:
        required: false
        type: string
      platform-file-extension:
        required: false
        type: string
      custom-project-file:
        required: false
        type: string
      editor-download-url:
        required: true
        type: string
      template-download-url:
        required: true
        type: string
    outputs:
      url:
        value: ${{ jobs.client-build-tool.outputs.url }}
      file-name:
        value: ${{ jobs.client-build-tool.outputs.file-name }}
      version:
        value: ${{ jobs.client-build-tool.outputs.version }}
    secrets:
      # only required when you deploy
      GCP_DEPLOYMENT_SECRET:
        required: false

# declare these so that they can be populated by the app
env:
  app_platform:
  app_ver:
  url: ${{ inputs.url }}


# we ensure our windows runners use bash always.
defaults:
  run:
    shell: bash
    # working-directory: ./mirror-godot-app

jobs:
  client-build-tool:
    name: Build
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 65
    outputs:
      url: ${{ steps.output-url.outputs.url }}
      file-name: ${{ steps.output-file-name.outputs.file-name }}
      version: ${{ steps.output-version.outputs.version }}
    steps:
      - name: Cleanup working directory (git version differences break the clean command otherwise)
        run: |
          shopt -s dotglob # includes all hidden files
          rm -rf ./*

      - uses: actions/checkout@v4
        with:
          path: app-clone/

      - name: Installing coreutils (for gtimeout)
        if: ${{ inputs.should-install-timeout-macos }}
        run: brew install coreutils

      - name: Fix working directory
        run: |
          ls -lah
          shopt -s dotglob # includes all hidden files
          mv ./app-clone/mirror-godot-app/* .
          ls -lah

      - name: Use custom project file (required for custom splash screen)
        if: ${{ inputs.custom-project-file }}
        run: |
          rm -Rf project.godot
          mv ${{ inputs.custom-project-file }} project.godot

      - name: Download editor and template
        run: |
          curl ${{ inputs.editor-download-url }} > ${{ inputs.editor-binary-download }}
          curl ${{ inputs.template-download-url }} > ${{ inputs.template-binary-name }}

      - name: Unzip editor binary
        if: ${{ inputs.should-unzip-editor }}
        run: |
          unzip -o ${{ inputs.editor-binary-download }}

      - name: Set up template in system-wide editor data
        run: |
          chmod +x ./${{ inputs.template-binary-name }}
          mkdir -p ${{ inputs.editor-template-directory }}
          mv ./${{ inputs.template-binary-name }} ${{ inputs.editor-template-directory }}/${{ inputs.export-template-file }}

      - name: Copy environment configuration to override.cfg
        run: |
          ls -R .
          rm -Rf override.cfg
          cp ./addons/mirror_internal/env_configs/${{ inputs.game-environment-cfg-name }}.cfg override.cfg
          # must be removed before booting the app otherwise we overwrite the override.cfg
          rm -Rf addons/mirror_internal

      - name: Wait for import of all assets
        if: ${{ !inputs.should-install-timeout-macos }}
        run: |
          chmod +x ./${{ inputs.editor-binary-name }}
          timeout 3m ./${{ inputs.editor-binary-name }} --editor --headless || true;

      - name: Wait for import of all assets
        if: ${{ inputs.should-install-timeout-macos }}
        run: |
          chmod +x ./${{ inputs.editor-binary-name }}
          gtimeout 3m ./${{ inputs.editor-binary-name }} --editor --headless || true;

      - name: Unit Tests
        timeout-minutes: 15
        # disabled until we can fix gut
        if: false
        run: |
          chmod +x ./${{ inputs.editor-binary-name }}
          ./${{ inputs.editor-binary-name }} -s --path ./ addons/gut/gut_cmdln.gd --headless

      - name: Delete tests and other editor-only files
        run: |
          rm -Rf test
          rm -Rf addons/gut
          rm -Rf gha-creds-*.json # ensure no credentials are stored in the app.

      - name: Export game client
        timeout-minutes: 10
        run: |
          mkdir build/
          chmod +x ./${{ inputs.editor-binary-name }}
          ./${{ inputs.editor-binary-name }} \
              --headless \
              --export-release ${{ inputs.game-export-preset }} \
              "build/${{ inputs.game-binary-name }}";
          chmod -R +x build/

      - name: Retrieve version information from platform data
        run: |
          cd build/
          ls
          cat version.txt
          cat platform_name.txt
          ver=$(cat version.txt)
          platform=$(cat platform_name.txt)
          echo $ver
          echo $platform
          echo "app_ver=${ver}" >> $GITHUB_ENV
          echo "app_platform=${platform}" >> $GITHUB_ENV

      - uses: msys2/setup-msys2@v2
        if: ${{ inputs.os == 'windows-latest' }}
        with:
          update: true
          install: >-
            zip

      - name: Zip for client download
        if: ${{ inputs.os != 'windows-latest' }}
        run: |
          cd build/
          ls ./
          zip -r ${{env.app_platform}}.zip "${{ inputs.game-binary-name }}" *.pck

      - name: Zip for client download
        if: ${{ inputs.os == 'windows-latest' }}
        shell: msys2 {0}
        run: |
          cd build/
          ls ./
          zip -r ${{env.app_platform}}.zip "${{ inputs.game-binary-name }}" *.pck

      - name: Google Cloud Platform authentication
        if: ${{ inputs.should-deploy || inputs.should-deploy-as-server }}
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOYMENT_SECRET }}'

      - name: Upload build to GCP (for auto-updater)
        if: inputs.should-deploy
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: build/${{ env.app_platform }}.tar.gz
          destination: ${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/

      - name: Upload build to GCP (for users)
        if: inputs.should-deploy
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: build/${{ env.app_platform }}.zip
          destination: ${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/

      - name: Upload platform json to GCP
        if: inputs.should-deploy
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: build/${{ env.app_platform }}.json
          destination: ${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/

      - name: Upload server pck
        if: inputs.should-deploy-as-server
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: build/${{ inputs.server-pck-path }}
          destination: ${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/

      - name: Uploading server binary
        if: inputs.should-deploy-as-server
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: build/${{ inputs.game-binary-name }}
          destination: ${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/

      - id: output-url
        run: |
          echo "url=${{ inputs.bucket-name }}/versions/${{ env.app_ver }}/${{ env.app_platform }}${{ inputs.platform-file-extension }}" >> $GITHUB_OUTPUT

      - id: output-file-name
        run: |
          echo "file-name=${{ env.app_platform }}${{ inputs.platform-file-extension }}" >> $GITHUB_OUTPUT

      - id: output-version
        run: |
          echo "version=${{ env.app_ver }}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          path: |
            build/${{ inputs.game-binary-name }}
            build/*.pck
          name: ${{ env.app_platform }}-client
